version: '3'

includes:
 lib:
  taskfile: ./docs/Taskfile_artifact_validation.yaml
  flatten: true

tasks:
  build_base_image:
    sources:
      - development_tools/development_environments/base_image/*
    generates:
      - build/build_base_image.done
    cmds:
      - docker build -t ghcr.io/renn0xtek9/robot_base_image:0.0.1 development_tools/development_environments/base_image

  push_base_image:
    deps: [build_base_image]
    cmds:
      - docker ghcr.io/renn0xtek9/robot_base_image:0.0.1

  build_system_engineering_environment:
    sources:
      - development_tools/development_environments/system_engineering_environment/*
    generates:
      - build/build_system_engineering_environment.done
    deps: [build_base_image]
    cmds:
      - docker build -t ghcr.io/renn0xtek9/robot_system_engineering_environment:0.0.1 development_tools/development_environments/system_engineering_environment

  push_system_engineering_environment:
    deps: [build_system_engineering_environment]
    cmds:
      - docker ghcr.io/renn0xtek9/robot_system_engineering_environment:0.0.1
