- name: CharlieIndia (CI) GitHub Actions Runner - Setup
  hosts: "{{ target_host }}"
  become: yes
  vars:
    runner_user: github-runner
    runner_dir: /home/{{ runner_user }}/actions-runner
    repo_url: "https://github.com/renn0xtek9/robot"  
    runner_token: "{{ runner_token }}"

  tasks:
    - name: Create a dedicated user for the runner
      user:
        name: "{{ runner_user }}"
        shell: /bin/bash
        system: yes
        create_home: yes

    - name: Install dependencies
      apt:
        name: ["curl", "unzip", "jq"]
        state: present
      when: ansible_os_family == 'Debian'

    - name: Download GitHub runner
      ansible.builtin.get_url:
        url: "https://github.com/actions/runner/releases/download/v2.331.0/actions-runner-linux-x64-2.331.0.tar.gz"
        dest: "/tmp/runner.tar.gz"
        checksum: "{{ sha256_github_runner }}"
        mode: '0755'
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
      
    - name: Create runner directory in runner user folder 
      ansible.builtin.file:
        path: "{{ runner_dir }}"
        state: directory
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"

    - name: Extract runner
      unarchive:
        src: "/tmp/runner.tar.gz"
        dest: "{{ runner_dir }}"
        remote_src: yes
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"
      become: yes
      become_user: "{{ runner_user }}"

    - name: Configure runner
      command: "./config.sh --url {{ repo_url }} --token {{ runner_token }} --unattended --name {{ target_host }}"
      args:
        chdir: "{{ runner_dir }}"
      become_user: "{{ runner_user }}"
