name: Build runtime environement
on:
  workflow_call:
  
jobs:
    Build-all-development-environment:
        name: "Build all development environments"
        runs-on: self-hosted
        steps: 
            - uses: actions/checkout@v4
              with:
                path: _work_host/
            - name: Build base docker image 
              working-directory: /home/github-runner/actions-runner/_work/robot/robot/_work_host
              run: task build_base_image
            - name: Build software engineering image 
              working-directory: /home/github-runner/actions-runner/_work/robot/robot/_work_host
              run: task build_software_engineering_environment
            - name: Build system engineering image 
              working-directory: /home/github-runner/actions-runner/_work/robot/robot/_work_host
              run: task build_system_engineering_environment
