name: System design validation

on:
    pull_request:
        branches:
            master
        paths-ignore:
            - 'software/**'

permissions:
    contents: read
    pull-requests: read

jobs:
    update-environments:
        name: "Update environments"
        uses: ./.github/workflows/build_development_environments.yml

    system-design-artifacts-validation:
        name: "System design artifacts validation"
        needs:
            - update-environments
        if: ${{ always() && (needs.update-environments.result == 'success' || needs.update-environments.result == 'skipped') }}
        runs-on: self-hosted
        container:
            image: 192.168.178.39:5443/robot_system_engineering_environment:0.0.1
        steps: 
            - uses: actions/checkout@v4
              with:
                path: _work_system/
                ref: ${{ github.event.pull_request.head.sha }}
                submodules: recursive
            - name: Validate system design artifacts
              working-directory: /home/github-runner/actions-runner/_work/robot/robot/_work_system
              run: task validate_document_artifacts
            - name: Generate documentation
              working-directory: /home/github-runner/actions-runner/_work/robot/robot/_work_system
              run: task documentation
